/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Registration;

import Login.Login;
import Database.DbConnection;
import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.*;

/**
 *
 * @author Siddhanta
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        MainPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        JPanel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FirstName = new javax.swing.JTextField();
        LastName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AreaCode = new javax.swing.JTextField();
        PhNumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        RegisterBtn = new javax.swing.JButton();
        ResetBtn = new javax.swing.JButton();
        AgreeBox = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        LoginBtn = new javax.swing.JLabel();

        setTitle("Registration Form");
        setBackground(new java.awt.Color(204, 204, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        MainPanel.setBackground(new java.awt.Color(204, 204, 255));
        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        MainPanel.setLayout(new java.awt.GridBagLayout());

        jPanel4.setBackground(new java.awt.Color(51, 0, 51));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        JPanel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        JPanel1.setForeground(new java.awt.Color(255, 255, 255));
        JPanel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JPanel1.setText("REGISTRATION FORM");
        jPanel4.add(JPanel1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 301;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 60, 0, 89);
        MainPanel.add(jPanel4, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Name");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 30, 61, 33));

        FirstName.setBackground(new java.awt.Color(204, 204, 204));
        FirstName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        FirstName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.add(FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 31, 183, 33));

        LastName.setBackground(new java.awt.Color(204, 204, 204));
        LastName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LastName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 31, 183, 33));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("First Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 70, 95, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Last Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 70, 100, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("E-Mail Id");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 106, 61, 34));

        Email.setBackground(new java.awt.Color(204, 204, 204));
        Email.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 107, 384, 34));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Phone");
        jLabel5.setMaximumSize(new java.awt.Dimension(58, 20));
        jLabel5.setMinimumSize(new java.awt.Dimension(58, 20));
        jLabel5.setPreferredSize(new java.awt.Dimension(58, 20));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 174, 61, 34));

        AreaCode.setBackground(new java.awt.Color(204, 204, 204));
        AreaCode.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AreaCode.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        AreaCode.setMinimumSize(new java.awt.Dimension(64, 20));
        jPanel2.add(AreaCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 175, 70, 35));

        PhNumber.setBackground(new java.awt.Color(204, 204, 204));
        PhNumber.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PhNumber.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        PhNumber.setMinimumSize(new java.awt.Dimension(64, 20));
        jPanel2.add(PhNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 175, 300, 34));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Area Code");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 216, 82, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Phone Number");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 216, 161, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Password");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 252, -1, 29));

        Password.setBackground(new java.awt.Color(204, 204, 204));
        Password.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Password.setPreferredSize(new java.awt.Dimension(60, 20));
        jPanel2.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 252, 384, 36));

        RegisterBtn.setBackground(new java.awt.Color(255, 102, 102));
        RegisterBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        RegisterBtn.setForeground(new java.awt.Color(255, 255, 255));
        RegisterBtn.setText("Register");
        RegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBtnActionPerformed(evt);
            }
        });
        jPanel2.add(RegisterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 344, 114, 40));

        ResetBtn.setBackground(new java.awt.Color(153, 0, 153));
        ResetBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ResetBtn.setForeground(new java.awt.Color(255, 255, 255));
        ResetBtn.setText("Reset");
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });
        jPanel2.add(ResetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 344, 114, 40));

        AgreeBox.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        AgreeBox.setText("  I agree the above details are correct.");
        jPanel2.add(AgreeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 306, 322, -1));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel9.setText("Are you a member ?");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 170, -1));

        LoginBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LoginBtn.setForeground(new java.awt.Color(51, 51, 255));
        LoginBtn.setText("Log In");
        LoginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginBtnMouseClicked(evt);
            }
        });
        jPanel2.add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 60, 20));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 44;
        gridBagConstraints.ipady = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 60, 69, 89);
        MainPanel.add(jPanel2, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBtnActionPerformed
        // TODO add your handling code here:
        DbConnection db = new DbConnection();
        Connection conn = db.CreateDBConnection();

        String query = "INSERT INTO `registration_form`(`name`, `email`, `phnumber`, `password`, `agree`) VALUES (?,?,?,?,?);";
        try {
            PreparedStatement stmt = conn.prepareStatement(query);
            String fName = FirstName.getText();
            String lName = LastName.getText();
            // Validate For Alphabet
            if (!( fName.isEmpty() && lName.isEmpty()) ) {
                if (!(isAlphabet(fName) && isAlphabet(lName))) {
                    JOptionPane.showMessageDialog(JPanel1, "Please Enter a Valid Name.", "Alert", JOptionPane.WARNING_MESSAGE);
                    fName = "";
                    lName = "";
                }
            }
            String password = new String(Password.getPassword());
            // Validate for Email
            String email = Email.getText();
            if (!email.isEmpty()) {
                if (!isValidEmail(email)) {
                    JOptionPane.showMessageDialog(JPanel1, "Please Enter a valid Email ID.", "Alert", JOptionPane.WARNING_MESSAGE);
                    email = "";
                }
            }
            String acode = AreaCode.getText();
            String phnumber = PhNumber.getText();
            if (!( acode.isEmpty() && phnumber.isEmpty()) ) {
                if (!(isValidNumber(acode) && isValidNumber(phnumber))) {
                    JOptionPane.showMessageDialog(JPanel1, "Please Enter a Valid Number.", "Alert", JOptionPane.WARNING_MESSAGE);
                    acode = "";
                    phnumber = "";
                }
            }

            if (!(fName.isEmpty() || lName.isEmpty() || password.isEmpty() || email.isEmpty() || acode.isEmpty() || phnumber.isEmpty())) {

                String Name;
                Name = fName + " " + lName;
                String phNumber;
                phNumber = "+" + acode + " " + phnumber;

                stmt.setString(1, Name);
                stmt.setString(2, email);
                stmt.setString(3, phNumber);
                stmt.setString(4, password);
                if (AgreeBox.isSelected()) {
                    stmt.setString(5, "yes");
                    stmt.executeUpdate();
                    //Execute the query
                    JOptionPane.showMessageDialog(JPanel1, "Data inserted Successfully.");
                    // After Data inserted , all the fields get empty
                    FirstName.setText("");
                    LastName.setText("");
                    Email.setText("");
                    AreaCode.setText("");
                    PhNumber.setText("");
                    Password.setText("");
                    AgreeBox.setSelected(false);
                } else {
                    JOptionPane.showMessageDialog(JPanel1, "Please click on checkbox.", "Alert", JOptionPane.WARNING_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(JPanel1, "Please Fill up the all details.", "Alert", JOptionPane.WARNING_MESSAGE);
            }

            //Connection Closed
            conn.close();
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_RegisterBtnActionPerformed

    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
        // TODO add your handling code here:
        FirstName.setText("");
        LastName.setText("");
        Email.setText("");
        AreaCode.setText("");
        PhNumber.setText("");
        Password.setText("");
        AgreeBox.setSelected(false);
    }//GEN-LAST:event_ResetBtnActionPerformed

    private void LoginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBtnMouseClicked
        // TODO add your handling code here:
        Login.LoginPage();
    }//GEN-LAST:event_LoginBtnMouseClicked

    /**
     * @param input
     * @return
     */
    public static boolean isAlphabet(String input) {
        return Pattern.matches("[a-zA-Z]+", input);
    }
    public static boolean isValidEmail(String email) {
        Pattern pattern = Pattern.compile(EMAIL_REGEX);
        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
    }
    public static boolean isValidNumber(String input) {
        return Pattern.matches("[0-9]+", input);
    }

    public static void RegistrationForm() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }
    public static void main(String[] args) {
        RegistrationForm();
    }
    private static final String EMAIL_REGEX = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AgreeBox;
    private javax.swing.JTextField AreaCode;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField FirstName;
    private javax.swing.JLabel JPanel1;
    private javax.swing.JTextField LastName;
    private javax.swing.JLabel LoginBtn;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField PhNumber;
    private javax.swing.JButton RegisterBtn;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
